import type { SheetResourceDef } from './types'

export const SHEET_RESOURCES: SheetResourceDef[] = [
  {
    id: 'studio-projects',
    name: 'Studio Projects',
    label: 'Projects',
    description: 'Project registry — name, status, owner, phase, timeline',
    osField: 'projects',
    columns: [
      { key: 'id', label: 'ID', type: 'string', required: true },
      { key: 'slug', label: 'Slug', type: 'string', required: true },
      { key: 'name', label: 'Name', type: 'string', required: true },
      { key: 'status', label: 'Status', type: 'string', required: true },
      { key: 'owner', label: 'Owner', type: 'string', required: true },
      { key: 'client', label: 'Client', type: 'string', required: false },
      { key: 'location', label: 'Location', type: 'string', required: false },
      { key: 'phase', label: 'Phase', type: 'string', required: false },
      { key: 'timelineStatus', label: 'Timeline Status', type: 'string', required: false },
      { key: 'operationalNotes', label: 'Operational Notes', type: 'string', required: false },
    ],
  },
  {
    id: 'approvals',
    name: 'Approvals',
    label: 'Approvals',
    description: 'Approval workflow — track pending, approved, and rejected decisions',
    osField: 'approvals',
    columns: [
      { key: 'id', label: 'ID', type: 'string', required: true },
      { key: 'projectId', label: 'Project ID', type: 'string', required: true },
      { key: 'title', label: 'Title', type: 'string', required: true },
      { key: 'status', label: 'Status', type: 'string', required: true },
      { key: 'owner', label: 'Owner', type: 'string', required: true },
      { key: 'dueDate', label: 'Due Date', type: 'date', required: false },
      { key: 'requestedBy', label: 'Requested By', type: 'string', required: false },
      { key: 'notes', label: 'Notes', type: 'string', required: false },
    ],
  },
  {
    id: 'capital-records',
    name: 'Capital Records',
    label: 'Capital Records',
    description: 'Finance ledger entries — income, expense, transfers',
    osField: 'financeLedgerRows',
    columns: [
      { key: 'id', label: 'ID', type: 'string', required: true },
      { key: 'label', label: 'Label', type: 'string', required: true },
      { key: 'amountTHB', label: 'Amount (THB)', type: 'number', required: true },
      { key: 'direction', label: 'Direction', type: 'string', required: true },
      { key: 'category', label: 'Category', type: 'string', required: true },
      { key: 'occurredAt', label: 'Date', type: 'date', required: true },
      { key: 'status', label: 'Status', type: 'string', required: false },
    ],
  },
  {
    id: 'investment-holdings',
    name: 'Investment Holdings',
    label: 'Holdings',
    description: 'Portfolio holdings — asset, quantity, cost, allocation',
    osField: 'holdings',
    columns: [
      { key: 'id', label: 'ID', type: 'string', required: true },
      { key: 'assetId', label: 'Asset ID', type: 'string', required: true },
      { key: 'quantity', label: 'Quantity', type: 'number', required: true },
      { key: 'averageCost', label: 'Avg Cost', type: 'number', required: true },
      { key: 'marketValueTHB', label: 'Market Value THB', type: 'number', required: false },
      { key: 'allocationPercent', label: 'Allocation %', type: 'number', required: false },
      { key: 'targetAllocationPercent', label: 'Target Allocation %', type: 'number', required: false },
      { key: 'currentPosture', label: 'Current Posture', type: 'string', required: false },
      { key: 'risk', label: 'Risk', type: 'string', required: false },
      { key: 'notes', label: 'Notes', type: 'string', required: false },
    ],
  },
  {
    id: 'allocation-buckets',
    name: 'Allocation Buckets',
    label: 'Allocation',
    description: 'Target allocation buckets — asset class, target %, current %',
    osField: 'allocationBuckets',
    importEnabled: false,
    columns: [
      { key: 'id', label: 'ID', type: 'string', required: true },
      { key: 'bucket', label: 'Bucket', type: 'string', required: true },
      { key: 'targetPercent', label: 'Target %', type: 'number', required: true },
      { key: 'currentPercent', label: 'Current %', type: 'number', required: true },
      { key: 'posture', label: 'Posture', type: 'string', required: false },
    ],
  },
  {
    id: 'ai-context-logs',
    name: 'AI Context Logs',
    label: 'AI Contexts',
    description: 'AI context export log — module, title, summary, tags',
    osField: 'aiContexts',
    columns: [
      { key: 'id', label: 'ID', type: 'string', required: true },
      { key: 'module', label: 'Module', type: 'string', required: true },
      { key: 'title', label: 'Title', type: 'string', required: true },
      { key: 'body', label: 'Body', type: 'string', required: false },
      { key: 'createdAt', label: 'Created', type: 'date', required: true },
    ],
  },
]
