import type { ComponentMeta } from '../types'

export const components: ComponentMeta[] = [
  {
    id: 'operational-status-chip',
    name: 'OperationalStatusChip',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/OperationalStatusChip.tsx',
    usedIn: ['SourceHealthMonitor', 'CommandCenterPage', 'BridgeSettingsPage', 'DivisionTile'],
    description: 'Status indicator chip showing health/watch/atRisk/blocked/complete with dot, icon, and label.',
    usageRule: 'Use for any entity that has a single operational status. Do not use for multi-status or progress.',
    do: ['Use with OperationalStatus type from visual-language.ts', 'Pair with status dot for quick scanning', 'Use sm variant inside tables and dense lists'],
    doNot: ['Do not use for numeric metrics', 'Do not animate the dot', 'Do not change the color mapping'],
    tags: ['status', 'badge', 'chip', 'indicator'],
  },
  {
    id: 'empty-state',
    name: 'EmptyState',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/EmptyState.tsx',
    usedIn: ['StudioWorkspacePage', 'InvestmentsPage', 'StudioProjectDetailPage', 'FinancePage'],
    description: 'Reusable empty state placeholder with title, body, optional action button, and icon.',
    usageRule: 'Use when a data-driven section has zero items to display. Always provide a helpful message.',
    do: ['Provide a clear title explaining what is empty', 'Add a body with next-step guidance', 'Use action button when user can create the first item'],
    doNot: ['Do not use for loading states', 'Do not use for error states', 'Do not stack multiple empty states'],
    tags: ['empty', 'placeholder', 'state'],
  },
  {
    id: 'workspace-drawer',
    name: 'WorkspaceDrawer',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/WorkspaceDrawer.tsx',
    usedIn: ['OSLayout', 'InvestmentsPage', 'StudioWorkspacePage', 'CommandCenterPage'],
    description: 'Slide-over drawer panel for secondary content. Opens from right edge.',
    usageRule: 'Use for detail views, forms, and secondary workflows that dont need a full page.',
    do: ['Use for edit forms and detail views', 'Provide a clear title', 'Use close button and ESC to dismiss'],
    doNot: ['Do not use for navigation', 'Do not stack multiple drawers', 'Do not put primary actions inside'],
    tags: ['drawer', 'panel', 'overlay'],
  },
  {
    id: 'source-health-monitor',
    name: 'SourceHealthMonitor',
    category: 'composite',
    status: 'production',
    owner: 'ds-team',
    version: '2.0.0',
    source: 'src/components/shared/SourceHealthMonitor.tsx',
    usedIn: ['CommandCenterPage', 'BridgeSettingsPage'],
    description: 'Health monitoring panel showing per-resource status derived from bridge diagnostics and import counts.',
    usageRule: 'Shows healthy/atRisk/disconnected per resource. Use on admin and bridge pages only.',
    do: ['Show all bridge resources in a scrollable list', 'Color-code by health status', 'Show last-success timestamps'],
    doNot: ['Do not show on public pages', 'Do not include in user-facing dashboards'],
    tags: ['health', 'monitor', 'bridge', 'status'],
  },
  {
    id: 'operating-rhythm',
    name: 'OperatingRhythm',
    category: 'workspace',
    status: 'beta',
    owner: 'studio',
    version: '1.0.0',
    source: 'src/components/studio/OperatingRhythm.tsx',
    usedIn: ['StudioWorkspacePage'],
    description: 'Studio operating rhythm gauge showing weekly pulse, task flow, and review cadence.',
    usageRule: 'Display at the top of the Studio overview page.',
    do: ['Show current week metrics', 'Highlight overdue items', 'Keep density high'],
    doNot: ['Do not show more than 7 days of data', 'Do not add charts or graphs'],
    tags: ['studio', 'rhythm', 'operations'],
  },
  {
    id: 'executive-dashboard',
    name: 'ExecutiveDashboard',
    category: 'workspace',
    status: 'beta',
    owner: 'studio',
    version: '1.0.0',
    source: 'src/components/studio/ExecutiveDashboard.tsx',
    usedIn: ['StudioWorkspacePage'],
    description: 'High-level studio KPI dashboard showing active projects, deadlines, and resource load.',
    usageRule: 'Top-level studio exec view. Show summary cards only.',
    do: ['Surface at-risk projects', 'Show deadline density', 'Keep to 4-6 KPIs'],
    doNot: ['Do not show per-project detail', 'Do not include financial data'],
    tags: ['studio', 'dashboard', 'kpi'],
  },
  {
    id: 'studio-timeline-board',
    name: 'StudioTimelineBoard',
    category: 'workspace',
    status: 'beta',
    owner: 'studio',
    version: '1.0.0',
    source: 'src/components/studio/StudioTimelineBoard.tsx',
    usedIn: ['StudioWorkspacePage'],
    description: 'Gantt-style timeline board showing project phases, milestones, and overlaps.',
    usageRule: 'Full-width board view for the timeline tab.',
    do: ['Show phases as colored bars', 'Show milestones as diamonds', 'Highlight conflicts in red'],
    doNot: ['Do not make interactive (read-only)', 'Do not show more than 12 months'],
    tags: ['studio', 'timeline', 'gantt'],
  },
  {
    id: 'portfolio-bucket-view',
    name: 'PortfolioBucketView',
    category: 'composite',
    status: 'production',
    owner: 'finance',
    version: '2.0.0',
    source: 'src/components/investments/PortfolioBucketView.tsx',
    usedIn: ['InvestmentsPage'],
    description: 'Strategy-bucket portfolio view. Groups holdings by investment strategy with allocation, drift, and actions.',
    usageRule: 'Main holdings view on the Investments page.',
    do: ['Show bucket name and allocation percent', 'Color-drift indicators red/green', 'Show per-asset gain/loss in USD'],
    doNot: ['Do not show more than 8 buckets', 'Do not make editable in read-only mode'],
    tags: ['finance', 'portfolio', 'bucket'],
  },
  {
    id: 'allocation-donut',
    name: 'AllocationDonut',
    category: 'primitive',
    status: 'production',
    owner: 'finance',
    version: '1.0.0',
    source: 'src/components/investments/AllocationDonut.tsx',
    usedIn: ['InvestmentsPage'],
    description: 'Donut chart showing portfolio allocation by strategy bucket.',
    usageRule: 'Use on allocation tab alongside AllocationComparison.',
    do: ['Use bucket colors consistently', 'Show percentages in tooltip', 'Keep size between 160-220px'],
    doNot: ['Do not animate', 'Do not use for non-portfolio data'],
    tags: ['chart', 'allocation', 'donut'],
  },
  {
    id: 'rebalance-preview',
    name: 'RebalancePreview',
    category: 'composite',
    status: 'production',
    owner: 'finance',
    version: '1.0.0',
    source: 'src/components/investments/RebalancePreview.tsx',
    usedIn: ['InvestmentsPage'],
    description: 'Rebalance suggestion list showing buy/sell/hold actions per asset.',
    usageRule: 'Collapsed by default showing top 5. Toggle to view all.',
    do: ['Group by action type', 'Show current vs target allocation', 'Flag high-priority items'],
    doNot: ['Do not auto-execute trades', 'Do not include in read-only views'],
    tags: ['finance', 'rebalance', 'allocation'],
  },
  {
    id: 'jarvis-b-model',
    name: 'JarvisBModel',
    category: 'composite',
    status: 'production',
    owner: 'command-center',
    version: '1.0.0',
    source: 'src/core/jarvis/buildJarvisBModel.ts',
    usedIn: ['CommandCenterPage'],
    description: 'System summary model aggregating all divisions into mood, priorities, executive brief, and agents.',
    usageRule: 'Built once per page load. Read-only aggregation.',
    do: ['Derive system mood from worst division mood', 'Surface top priorities from reviews and stale sources', 'Generate executive brief dynamically'],
    doNot: ['Do not modify OsData', 'Do not trigger side effects', 'Do not expose to user editing'],
    tags: ['system', 'model', 'aggregator'],
  },
  {
    id: 'division-tile',
    name: 'DivisionTile',
    category: 'composite',
    status: 'production',
    owner: 'command-center',
    version: '1.0.0',
    source: 'src/components/command-center/DivisionTile.tsx',
    usedIn: ['CommandCenterPage'],
    description: 'Division card with icon, mood dot, stats grid, micro progress bar, and metric badges.',
    usageRule: 'Used in the Division Matrix grid. Each card links to the division detail page.',
    do: ['Show division icon and accent color', 'Include mood indicator dot with pulse', 'Show key metrics as compact badges'],
    doNot: ['Do not exceed 2 columns in the grid', 'Do not add hover animations beyond color shift'],
    tags: ['division', 'card', 'matrix'],
  },
]
