import type { ComponentMeta } from '../types'

export const components: ComponentMeta[] = [
  {
    id: 'operational-status-chip',
    name: 'OperationalStatusChip',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/OperationalStatusChip.tsx',
    usedIn: ['SourceHealthMonitor', 'CommandCenterPage', 'BridgeSettingsPage', 'DivisionTile'],
    description: 'Status indicator chip showing health/watch/atRisk/blocked/complete with dot, icon, and label.',
    usageRule: 'Use for any entity that has a single operational status. Do not use for multi-status or progress.',
    do: ['Use with OperationalStatus type from visual-language.ts', 'Pair with status dot for quick scanning', 'Use sm variant inside tables and dense lists'],
    doNot: ['Do not use for numeric metrics', 'Do not animate the dot', 'Do not change the color mapping'],
    tags: ['status', 'badge', 'chip', 'indicator'],
  },
  {
    id: 'empty-state',
    name: 'EmptyState',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/EmptyState.tsx',
    usedIn: ['StudioWorkspacePage', 'InvestmentsPage', 'StudioProjectDetailPage', 'FinancePage'],
    description: 'Reusable empty state placeholder with title, body, optional action button, and icon.',
    usageRule: 'Use when a data-driven section has zero items to display. Always provide a helpful message.',
    do: ['Provide a clear title explaining what is empty', 'Add a body with next-step guidance', 'Use action button when user can create the first item'],
    doNot: ['Do not use for loading states', 'Do not use for error states', 'Do not stack multiple empty states'],
    tags: ['empty', 'placeholder', 'state'],
  },
  {
    id: 'workspace-drawer',
    name: 'WorkspaceDrawer',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/WorkspaceDrawer.tsx',
    usedIn: ['OSLayout', 'InvestmentsPage', 'StudioWorkspacePage', 'CommandCenterPage'],
    description: 'Slide-over drawer panel for secondary content. Opens from right edge.',
    usageRule: 'Use for detail views, forms, and secondary workflows that dont need a full page.',
    do: ['Use for edit forms and detail views', 'Provide a clear title', 'Use close button and ESC to dismiss'],
    doNot: ['Do not use for navigation', 'Do not stack multiple drawers', 'Do not put primary actions inside'],
    tags: ['drawer', 'panel', 'overlay'],
  },
  {
    id: 'source-health-monitor',
    name: 'SourceHealthMonitor',
    category: 'composite',
    status: 'production',
    owner: 'ds-team',
    version: '2.0.0',
    source: 'src/components/shared/SourceHealthMonitor.tsx',
    usedIn: ['CommandCenterPage', 'BridgeSettingsPage'],
    description: 'Health monitoring panel showing per-resource status derived from bridge diagnostics and import counts.',
    usageRule: 'Shows healthy/atRisk/disconnected per resource. Use on admin and bridge pages only.',
    do: ['Show all bridge resources in a scrollable list', 'Color-code by health status', 'Show last-success timestamps'],
    doNot: ['Do not show on public pages', 'Do not include in user-facing dashboards'],
    tags: ['health', 'monitor', 'bridge', 'status'],
  },
  {
    id: 'operating-rhythm',
    name: 'OperatingRhythm',
    category: 'workspace',
    status: 'beta',
    owner: 'studio',
    version: '1.0.0',
    source: 'src/components/studio/OperatingRhythm.tsx',
    usedIn: ['StudioWorkspacePage'],
    description: 'Studio operating rhythm gauge showing weekly pulse, task flow, and review cadence.',
    usageRule: 'Display at the top of the Studio overview page.',
    do: ['Show current week metrics', 'Highlight overdue items', 'Keep density high'],
    doNot: ['Do not show more than 7 days of data', 'Do not add charts or graphs'],
    tags: ['studio', 'rhythm', 'operations'],
  },
  {
    id: 'executive-dashboard',
    name: 'ExecutiveDashboard',
    category: 'workspace',
    status: 'beta',
    owner: 'studio',
    version: '1.0.0',
    source: 'src/components/studio/ExecutiveDashboard.tsx',
    usedIn: ['StudioWorkspacePage'],
    description: 'High-level studio KPI dashboard showing active projects, deadlines, and resource load.',
    usageRule: 'Top-level studio exec view. Show summary cards only.',
    do: ['Surface at-risk projects', 'Show deadline density', 'Keep to 4-6 KPIs'],
    doNot: ['Do not show per-project detail', 'Do not include financial data'],
    tags: ['studio', 'dashboard', 'kpi'],
  },
  {
    id: 'studio-timeline-board',
    name: 'StudioTimelineBoard',
    category: 'workspace',
    status: 'beta',
    owner: 'studio',
    version: '1.0.0',
    source: 'src/components/studio/StudioTimelineBoard.tsx',
    usedIn: ['StudioWorkspacePage'],
    description: 'Gantt-style timeline board showing project phases, milestones, and overlaps.',
    usageRule: 'Full-width board view for the timeline tab.',
    do: ['Show phases as colored bars', 'Show milestones as diamonds', 'Highlight conflicts in red'],
    doNot: ['Do not make interactive (read-only)', 'Do not show more than 12 months'],
    tags: ['studio', 'timeline', 'gantt'],
  },
  {
    id: 'portfolio-bucket-view',
    name: 'PortfolioBucketView',
    category: 'composite',
    status: 'production',
    owner: 'finance',
    version: '2.0.0',
    source: 'src/components/investments/PortfolioBucketView.tsx',
    usedIn: ['InvestmentsPage'],
    description: 'Strategy-bucket portfolio view. Groups holdings by investment strategy with allocation, drift, and actions.',
    usageRule: 'Main holdings view on the Investments page.',
    do: ['Show bucket name and allocation percent', 'Color-drift indicators red/green', 'Show per-asset gain/loss in USD'],
    doNot: ['Do not show more than 8 buckets', 'Do not make editable in read-only mode'],
    tags: ['finance', 'portfolio', 'bucket'],
  },
  {
    id: 'allocation-donut',
    name: 'AllocationDonut',
    category: 'primitive',
    status: 'production',
    owner: 'finance',
    version: '1.0.0',
    source: 'src/components/investments/AllocationDonut.tsx',
    usedIn: ['InvestmentsPage'],
    description: 'Donut chart showing portfolio allocation by strategy bucket.',
    usageRule: 'Use on allocation tab alongside AllocationComparison.',
    do: ['Use bucket colors consistently', 'Show percentages in tooltip', 'Keep size between 160-220px'],
    doNot: ['Do not animate', 'Do not use for non-portfolio data'],
    tags: ['chart', 'allocation', 'donut'],
  },
  {
    id: 'rebalance-preview',
    name: 'RebalancePreview',
    category: 'composite',
    status: 'production',
    owner: 'finance',
    version: '1.0.0',
    source: 'src/components/investments/RebalancePreview.tsx',
    usedIn: ['InvestmentsPage'],
    description: 'Rebalance suggestion list showing buy/sell/hold actions per asset.',
    usageRule: 'Collapsed by default showing top 5. Toggle to view all.',
    do: ['Group by action type', 'Show current vs target allocation', 'Flag high-priority items'],
    doNot: ['Do not auto-execute trades', 'Do not include in read-only views'],
    tags: ['finance', 'rebalance', 'allocation'],
  },
  {
    id: 'jarvis-b-model',
    name: 'JarvisBModel',
    category: 'composite',
    status: 'production',
    owner: 'command-center',
    version: '1.0.0',
    source: 'src/core/jarvis/buildJarvisBModel.ts',
    usedIn: ['CommandCenterPage'],
    description: 'System summary model aggregating all divisions into mood, priorities, executive brief, and agents.',
    usageRule: 'Built once per page load. Read-only aggregation.',
    do: ['Derive system mood from worst division mood', 'Surface top priorities from reviews and stale sources', 'Generate executive brief dynamically'],
    doNot: ['Do not modify OsData', 'Do not trigger side effects', 'Do not expose to user editing'],
    tags: ['system', 'model', 'aggregator'],
  },
  {
    id: 'division-tile',
    name: 'DivisionTile',
    category: 'composite',
    status: 'production',
    owner: 'command-center',
    version: '1.0.0',
    source: 'src/components/command-center/DivisionTile.tsx',
    usedIn: ['CommandCenterPage'],
    description: 'Division card with icon, mood dot, stats grid, micro progress bar, and metric badges.',
    usageRule: 'Used in the Division Matrix grid. Each card links to the division detail page.',
    do: ['Show division icon and accent color', 'Include mood indicator dot with pulse', 'Show key metrics as compact badges'],
    doNot: ['Do not exceed 2 columns in the grid', 'Do not add hover animations beyond color shift'],
    tags: ['division', 'card', 'matrix'],
  },
  {
    id: 'workspace-shell',
    name: 'WorkspaceShell',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/workspace/WorkspaceShell.tsx',
    usedIn: ['DesignSystemPage'],
    description: 'Page-level shell with optional sidebar and main content area.',
    usageRule: 'Use as the outermost layout wrapper for workspace pages.',
    do: ['Provide sidebar slot for navigation or metadata panels', 'Keep main content area flexible'],
    doNot: ['Do not nest multiple shells', 'Do not use inside drawers'],
    tags: ['layout', 'shell', 'workspace'],
  },
  {
    id: 'workspace-header',
    name: 'WorkspaceHeader',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/workspace/WorkspaceHeader.tsx',
    usedIn: ['DesignSystemPage'],
    description: 'Section header with label, title, and action slot.',
    usageRule: 'Use at the top of workspace sections.',
    do: ['Show section label in muted meta text', 'Show title prominently', 'Slot actions on the right'],
    doNot: ['Do not use without a title', 'Do not add more than 2-3 actions'],
    tags: ['header', 'section', 'workspace'],
    implementationStatus: 'standalone',
  },
  {
    id: 'workspace-card',
    name: 'WorkspaceCard',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/workspace/WorkspaceCard.tsx',
    usedIn: ['DesignSystemPage'],
    description: 'Content card with optional accent border. Available in default and subdued variants.',
    usageRule: 'Use for grouped content within workspace panels.',
    do: ['Use accent variant for highlight items', 'Tags at bottom for metadata'],
    doNot: ['Do not nest cards more than 2 levels deep'],
    tags: ['card', 'content', 'workspace'],
    implementationStatus: 'standalone',
  },
  {
    id: 'workspace-section',
    name: 'WorkspaceSection',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/workspace/WorkspaceSection.tsx',
    usedIn: ['StudioWorkspacePage'],
    description: 'Section wrapper with panel styling. Supports card, float, and plain variants.',
    usageRule: 'Use as section container for grouped content. Pass header as prop for consistent section headers.',
    do: ['Use variant="float" for elevated sections', 'Pass WorkspaceHeader as header prop'],
    doNot: ['Do not nest more than 2 levels deep'],
    tags: ['section', 'panel', 'layout'],
    introduced: '2.0.0',
    implementationStatus: 'standalone',
  },
  {
    id: 'status-rail',
    name: 'StatusRail',
    category: 'workspace',
    status: 'production',
    owner: 'command-center',
    version: '1.0.0',
    source: 'src/components/shared/workspace/StatusRail.tsx',
    usedIn: ['CommandCenterPage', 'DesignSystemPage'],
    description: 'Compact horizontal strip showing status badges with dots.',
    usageRule: 'Use for system status overview, division moods, or batch status displays.',
    do: ['Show 3-8 status items', 'Use colored dots for quick scanning', 'Wrap naturally on narrow screens'],
    doNot: ['Do not use for interactive filters', 'Do not exceed 12 items'],
    tags: ['status', 'rail', 'strip'],
    implementationStatus: 'standalone',
  },
  {
    id: 'metric-strip',
    name: 'MetricStrip',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/workspace/MetricStrip.tsx',
    usedIn: ['CommandCenterPage', 'InvestmentsPage', 'DesignSystemPage'],
    description: 'Row of compact metric cards showing key-value pairs.',
    usageRule: 'Use for top-level KPIs in page headers or section summaries.',
    do: ['Show 3-6 metrics', 'Right-align numeric values', 'Color-code significant values'],
    doNot: ['Do not exceed 8 metrics', 'Do not add icons or badges inside'],
    tags: ['metric', 'kpi', 'strip'],
    implementationStatus: 'standalone',
  },
  {
    id: 'activity-feed',
    name: 'ActivityFeed',
    category: 'workspace',
    status: 'production',
    owner: 'command-center',
    version: '1.0.0',
    source: 'src/components/shared/workspace/ActivityFeed.tsx',
    usedIn: ['CommandCenterPage', 'DesignSystemPage'],
    description: 'Vertical timeline of system or user activities with status dots.',
    usageRule: 'Use for recent activity logs, agent updates, or event streams.',
    do: ['Show timestamp', 'Use status dot colors', 'Keep entries to 3-8 items'],
    doNot: ['Do not show more than 20 items without pagination', 'Do not make editable'],
    tags: ['activity', 'feed', 'timeline'],
    implementationStatus: 'standalone',
  },
  {
    id: 'data-list',
    name: 'DataList',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/workspace/DataList.tsx',
    usedIn: ['every page'],
    description: 'Standard data table with consistent column alignment, header styling, and row states.',
    usageRule: 'Use for tabular data display. Right-align numeric columns.',
    do: ['Left-align text columns', 'Right-align numeric columns', 'Use pill/badge for status columns'],
    doNot: ['Do not add horizontal scroll without overflow-x-auto wrapper'],
    tags: ['table', 'list', 'data'],
  },
  {
    id: 'empty-state',
    name: 'EmptyState',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/EmptyState.tsx',
    usedIn: ['every page'],
    description: 'Empty state placeholder with title, description, and optional action.',
    usageRule: 'Show when a data-driven section has zero items.',
    do: ['Provide clear title', 'Add next-step guidance', 'Use action button for creating first item'],
    doNot: ['Do not use for loading or error states'],
    tags: ['empty', 'state', 'placeholder'],
  },
  {
    id: 'filter-bar',
    name: 'FilterBar',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/workspace/FilterBar.tsx',
    usedIn: ['DesignSystemPage'],
    description: 'Compact horizontal bar with search input and filter toggles.',
    usageRule: 'Use above DataList or content areas that support filtering.',
    do: ['Place search on the left', 'Use pill badges for active filter count'],
    doNot: ['Do not add more than 6 filter options inline'],
    tags: ['filter', 'search', 'toolbar'],
  },
  {
    id: 'notice-banner',
    name: 'NoticeBanner',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/workspace/NoticeBanner.tsx',
    usedIn: ['DesignSystemPage'],
    description: 'Inline notice banner for warnings, updates, or action-required messages.',
    usageRule: 'Use sparingly for important system messages.',
    do: ['Color by severity', 'Keep text concise', 'Use icon prefix'],
    doNot: ['Do not stack more than 2 banners', 'Do not use for promotional content'],
    tags: ['notice', 'banner', 'alert'],
  },
  {
    id: 'loading-state',
    name: 'LoadingState',
    category: 'workspace',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/workspace/LoadingState.tsx',
    usedIn: ['DesignSystemPage'],
    description: 'Loading indicator with spinner and optional skeleton placeholders.',
    usageRule: 'Show during async data fetches.',
    do: ['Show spinner for short loads', 'Show skeleton for expected content shape', 'Keep animations subtle'],
    doNot: ['Do not show for more than 10 seconds without error handling'],
    tags: ['loading', 'skeleton', 'state'],
  },
  {
    id: 'grid-overlay',
    name: 'GridOverlay',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/GridOverlay.tsx',
    usedIn: ['OSLayout', 'DesignSystemPage'],
    description: 'Spatial grid overlay for layout alignment reference. Four variants: architect, operation, presentation, print. Supports shell mode for page background.',
    usageRule: 'Enable during layout design and review. Never interactive. Always below content.',
    do: ['Use architect variant for design review', 'Use operation variant for daily use', 'Fade edges for natural appearance'],
    doNot: ['Do not make interactive', 'Do not place above content', 'Do not use opacity above 0.1'],
    tags: ['grid', 'layout', 'reference', 'background'],
    introduced: '2.0.0',
  },
  {
    id: 'grid-canvas',
    name: 'GridCanvas',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/GridCanvas.tsx',
    usedIn: ['DesignSystemPage'],
    description: 'Wrapper component that automatically injects GridOverlay behind child content.',
    usageRule: 'Use as page-level wrapper when grid reference is needed during layout review.',
    do: ['Wrap pages under active layout review', 'Use with gridEnabled prop'],
    doNot: ['Do not use on production without explicit toggle', 'Do not nest multiple GridCanvas'],
    tags: ['grid', 'wrapper', 'canvas'],
    introduced: '2.0.0',
  },
  {
    id: 'color-tokens',
    name: 'ColorTokens',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '2.0.0',
    source: 'src/design-system/foundations/colors.ts',
    usedIn: ['DesignSystemPage'],
    description: 'Semantic color tokens — brand, surface, text, status, overlay.',
    usageRule: 'Reference by CSS variable. Never hardcode HEX values outside design tokens.',
    do: ['Use --bb-accent for primary actions', 'Use --bb-surface-2/3 for card backgrounds', 'Use semantic tokens (--bb-green, --bb-red) for status'],
    doNot: ['Do not reference CSS variables from components', 'Do not add new colors without registry update'],
    tags: ['tokens', 'color', 'foundation'],
  },
  {
    id: 'typography-tokens',
    name: 'TypographyTokens',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '2.0.0',
    source: 'src/design-system/foundations/typography.ts',
    usedIn: ['DesignSystemPage'],
    description: 'Typography scale — Display XL through Mono Small with size, weight, line-height.',
    usageRule: 'Use predefined type tokens only. Do not add custom font sizes.',
    do: ['Use Display XL/LG for page titles', 'Use Body for default text', 'Use Mono for metrics and code'],
    doNot: ['Do not mix font families', 'Do not use weights outside the defined scale'],
    tags: ['tokens', 'typography', 'foundation'],
  },
  {
    id: 'spacing-tokens',
    name: 'SpacingTokens',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '2.0.0',
    source: 'src/design-system/foundations/spacing.ts',
    usedIn: ['DesignSystemPage'],
    description: 'Spacing scale from 2px to 64px with padding, gap, and margin examples.',
    usageRule: 'Use spacing scale consistently. Prefer defined tokens over arbitrary values.',
    do: ['Use spacing for padding, margin, and gap', 'Follow 8px grid where possible'],
    doNot: ['Do not use odd spacing values outside the scale'],
    tags: ['tokens', 'spacing', 'foundation'],
  },
  {
    id: 'spatial-provider',
    name: 'SpatialProvider',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/SpatialProvider.tsx',
    usedIn: ['OSLayout'],
    description: 'Provides spatial context (grid variant, spacing rhythm, column definitions) to all child components via React context.',
    usageRule: 'Wrap at OS layout level. Grid mode is automatically derived from route path.',
    do: ['Let SpatialProvider derive grid mode from route', 'Consume with useSpatial() hook', 'Use grid debug mode (Ctrl+Shift+G) for verification'],
    doNot: ['Do not nest multiple SpatialProviders', 'Do not override config without understanding the spatial system'],
    tags: ['spatial', 'provider', 'context', 'grid'],
    introduced: '2.0.0',
  },
  {
    id: 'use-spatial',
    name: 'useSpatial',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/design/spatial.ts',
    usedIn: ['WorkspaceShell', 'SpatialProvider', 'GridDebug', 'OSLayout'],
    description: 'React hook returning current spatial config: grid variant, spacing rhythm, columns, and debug toggle.',
    usageRule: 'Call from any component within SpatialProvider. Returns { config, isDebugMode, toggleDebug }.',
    do: ['Use for reading current grid variant and rhythm', 'Use toggleDebug for development grid verification'],
    doNot: ['Do not call outside SpatialProvider', 'Do not modify config directly'],
    tags: ['spatial', 'hook', 'context'],
    introduced: '2.0.0',
  },
  {
    id: 'grid-debug',
    name: 'GridDebug',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/components/shared/GridDebug.tsx',
    usedIn: ['SpatialProvider'],
    description: 'Developer grid overlay showing column numbers, variant, and spacing info. Activated by Ctrl+Shift+G.',
    usageRule: 'Renders automatically inside SpatialProvider. Toggle with keyboard shortcut.',
    do: ['Use during layout review', 'Toggle with Ctrl+Shift+G'],
    doNot: ['Do not show in production screenshots', 'Do not make interactive'],
    tags: ['spatial', 'debug', 'grid', 'dev'],
    introduced: '2.0.0',
  },
]

