import type { ComponentMeta } from '../types'

export const primitives: ComponentMeta[] = [
  {
    id: 'pill',
    name: 'Pill',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Tailwind utility classes',
    usedIn: ['every page'],
    description: 'Small rounded badge for counts, labels, and status indicators. Available in multiple color variants.',
    usageRule: 'Use pill for count badges and status labels. Use pill-green/amber/accent for semantic coloring.',
    do: ['Use pill for secondary counts', 'Use pill-green for healthy/ok states', 'Use pill-amber for warnings'],
    doNot: ['Do not use pills for primary actions', 'Do not stack more than 3 pills inline'],
    tags: ['badge', 'pill', 'label'],
  },
  {
    id: 'panel',
    name: 'Panel',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Tailwind + CSS',
    usedIn: ['every page'],
    description: 'Card container with rounded corners, border, and optional background tint.',
    usageRule: 'Use panel for grouped content sections. Use panel-float for elevated cards.',
    do: ['Use panel-header for title and actions', 'Maintain consistent padding inside panels', 'Nest panels only one level deep'],
    doNot: ['Do not use panels inside drawers', 'Do not remove border-radius from panels'],
    tags: ['card', 'container', 'panel'],
  },
  {
    id: 'os-list-row',
    name: 'OsListRow',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'CSS class .os-list-row',
    usedIn: ['every page'],
    description: 'Standard list row with consistent padding, border, and hover state.',
    usageRule: 'Use for list/table rows in admin and detail pages.',
    do: ['Maintain consistent row height', 'Use hover state for clickable rows', 'Right-align numeric columns'],
    doNot: ['Do not use inside panels with different padding', 'Do not remove the bottom border on the last row'],
    tags: ['list', 'row', 'table'],
  },
  {
    id: 'os-progress',
    name: 'OsProgress',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'CSS classes .os-progress / .os-progress-bar-*',
    usedIn: ['CommandCenterPage', 'AgentQueueBoard'],
    description: 'Minimal progress bar with color variants for accent, amber, green, and neutral.',
    usageRule: 'Use os-progress as container, os-progress-bar-* for the fill.',
    do: ['Use color variants by state (accent=running, amber=waiting, green=done)', 'Keep height between 4-6px', 'Show percentage label to the right'],
    doNot: ['Do not animate the bar', 'Do not use for determinate progress only (no infinite)'],
    tags: ['progress', 'bar', 'indicator'],
  },
  {
    id: 'os-hero-metric',
    name: 'OsHeroMetric',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'CSS class .os-hero-metric',
    usedIn: ['CommandCenterPage', 'InvestmentsPage'],
    description: 'Hero metric card with icon, value, label, helper text, and optional progress bar.',
    usageRule: 'Use in page headers for top-level KPIs. Max 8 per page.',
    do: ['Show the most important number prominently', 'Include a helper explaining what the number means', 'Use progress to show proportion of a total'],
    doNot: ['Do not use for secondary metrics', 'Do not stack more than 8 in a row', 'Do not add hover effects'],
    tags: ['metric', 'hero', 'kpi'],
  },
  {
    id: 'mini',
    name: 'Mini',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Inline component',
    usedIn: ['InvestmentsPage', 'CommandCenterPage', 'DivisionDetailPage'],
    description: 'Compact metric label-value pair for dense data displays.',
    usageRule: 'Use inside panels and cards where space is limited.',
    do: ['Keep labels short (1-3 words)', 'Align numeric values right', 'Stack multiple mini in a grid'],
    doNot: ['Do not use standalone', 'Do not add icons or badges inside'],
    tags: ['metric', 'compact', 'label'],
  },
]
