import type { ComponentMeta } from '../types'

export const primitives: ComponentMeta[] = [
  {
    id: 'pill',
    name: 'Pill',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Tailwind utility classes',
    usedIn: ['every page'],
    description: 'Small rounded badge for counts, labels, and status indicators. Available in multiple color variants.',
    usageRule: 'Use pill for count badges and status labels. Use pill-green/amber/accent for semantic coloring.',
    do: ['Use pill for secondary counts', 'Use pill-green for healthy/ok states', 'Use pill-amber for warnings'],
    doNot: ['Do not use pills for primary actions', 'Do not stack more than 3 pills inline'],
    tags: ['badge', 'pill', 'label'],
  },
  {
    id: 'panel',
    name: 'Panel',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Tailwind + CSS',
    usedIn: ['every page'],
    description: 'Card container with rounded corners, border, and optional background tint.',
    usageRule: 'Use panel for grouped content sections. Use panel-float for elevated cards.',
    do: ['Use panel-header for title and actions', 'Maintain consistent padding inside panels', 'Nest panels only one level deep'],
    doNot: ['Do not use panels inside drawers', 'Do not remove border-radius from panels'],
    tags: ['card', 'container', 'panel'],
  },
  {
    id: 'os-list-row',
    name: 'OsListRow',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'CSS class .os-list-row',
    usedIn: ['every page'],
    description: 'Standard list row with consistent padding, border, and hover state.',
    usageRule: 'Use for list/table rows in admin and detail pages.',
    do: ['Maintain consistent row height', 'Use hover state for clickable rows', 'Right-align numeric columns'],
    doNot: ['Do not use inside panels with different padding', 'Do not remove the bottom border on the last row'],
    tags: ['list', 'row', 'table'],
  },
  {
    id: 'os-progress',
    name: 'OsProgress',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'CSS classes .os-progress / .os-progress-bar-*',
    usedIn: ['CommandCenterPage', 'AgentQueueBoard'],
    description: 'Minimal progress bar with color variants for accent, amber, green, and neutral.',
    usageRule: 'Use os-progress as container, os-progress-bar-* for the fill.',
    do: ['Use color variants by state (accent=running, amber=waiting, green=done)', 'Keep height between 4-6px', 'Show percentage label to the right'],
    doNot: ['Do not animate the bar', 'Do not use for determinate progress only (no infinite)'],
    tags: ['progress', 'bar', 'indicator'],
  },
  {
    id: 'os-hero-metric',
    name: 'OsHeroMetric',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'CSS class .os-hero-metric',
    usedIn: ['CommandCenterPage', 'InvestmentsPage'],
    description: 'Hero metric card with icon, value, label, helper text, and optional progress bar.',
    usageRule: 'Use in page headers for top-level KPIs. Max 8 per page.',
    do: ['Show the most important number prominently', 'Include a helper explaining what the number means', 'Use progress to show proportion of a total'],
    doNot: ['Do not use for secondary metrics', 'Do not stack more than 8 in a row', 'Do not add hover effects'],
    tags: ['metric', 'hero', 'kpi'],
  },
  {
    id: 'mini',
    name: 'Mini',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Inline component',
    usedIn: ['InvestmentsPage', 'CommandCenterPage', 'DivisionDetailPage'],
    description: 'Compact metric label-value pair for dense data displays.',
    usageRule: 'Use inside panels and cards where space is limited.',
    do: ['Keep labels short (1-3 words)', 'Align numeric values right', 'Stack multiple mini in a grid'],
    doNot: ['Do not use standalone', 'Do not add icons or badges inside'],
    tags: ['metric', 'compact', 'label'],
  },
  {
    id: 'button',
    name: 'Button',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Tailwind classes: btn / btn-primary',
    usedIn: ['every page'],
    description: 'Action button with default and primary variants. Supports disabled state.',
    usageRule: 'Use btn-primary for primary calls-to-action. Use btn for secondary actions.',
    do: ['Use btn-primary once per view', 'Disable buttons during async operations'],
    doNot: ['Do not use buttons for navigation (use Link)', 'Do not stack more than 3 primary buttons'],
    tags: ['button', 'action', 'input'],
  },
  {
    id: 'input',
    name: 'Input',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Styled HTML input element',
    usedIn: ['every page'],
    description: 'Text input with consistent border, padding, and focus styling.',
    usageRule: 'Use for single-line text entry. Always provide a label.',
    do: ['Use with visible label', 'Show placeholder text', 'Disable when not editable'],
    doNot: ['Do not use without a label or aria-label', 'Do not change border radius'],
    tags: ['input', 'form', 'field'],
  },
  {
    id: 'badge',
    name: 'Badge',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Custom CSS classes + tailwind',
    usedIn: ['every page'],
    description: 'Small indicator badge with optional dot, color variant, and border. Used for status, counts, and labels.',
    usageRule: 'Use badge for status indicators and metadata labels.',
    do: ['Use with dot for live/active states', 'Use green/amber/red for status semantics'],
    doNot: ['Do not use badges for primary navigation', 'Do not make badges interactive'],
    tags: ['badge', 'indicator', 'status'],
  },
  {
    id: 'tabs',
    name: 'Tabs',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Inline layout + CSS',
    usedIn: ['every page'],
    description: 'Horizontal tab bar with active underline indicator.',
    usageRule: 'Use for switching between content sections within a page.',
    do: ['Keep labels short (1-3 words)', 'Show active tab with accent underline'],
    doNot: ['Do not use more than 10 tabs', 'Do not nest tabs'],
    tags: ['tabs', 'navigation', 'section'],
  },
  {
    id: 'divider',
    name: 'Divider',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Tailwind border classes',
    usedIn: ['every page'],
    description: 'Horizontal or vertical divider line. Available in solid and dashed variants.',
    usageRule: 'Use to separate distinct content sections.',
    do: ['Use solid for major sections', 'Use dashed for subtle separation'],
    doNot: ['Do not use dividers inside cards', 'Do not stack multiple dividers'],
    tags: ['divider', 'separator', 'layout'],
  },
  {
    id: 'table',
    name: 'Table',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Styled HTML table element',
    usedIn: ['every page'],
    description: 'Standard HTML table with consistent header styling, row borders, and hover state.',
    usageRule: 'Use for structured data display with columns.',
    do: ['Left-align text content', 'Right-align numeric content', 'Use pill/badge in status columns'],
    doNot: ['Do not use tables for layout', 'Do not remove header row'],
    tags: ['table', 'grid', 'data'],
  },
  {
    id: 'progress-bar',
    name: 'ProgressBar',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'CSS classes: .progress / .progress-fill + color variants',
    usedIn: ['every page'],
    description: 'Determinate progress bar with accent, green, and amber color variants.',
    usageRule: 'Use for task completion, loading progress, or threshold indicators.',
    do: ['Show percentage label', 'Use color variants by state'],
    doNot: ['Do not animate deterministically', 'Do not use for infinite/indeterminate loading'],
    tags: ['progress', 'bar', 'indicator'],
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Animated placeholder divs',
    usedIn: ['DesignSystemPage'],
    description: 'Pulsing placeholder shapes for loading content.',
    usageRule: 'Use while content is being fetched asynchronously.',
    do: ['Match skeleton shape to expected content', 'Use subtle pulse animation'],
    doNot: ['Do not show for more than 10 seconds', 'Do not use for already-cached data'],
    tags: ['skeleton', 'loading', 'placeholder'],
  },
  {
    id: 'avatar',
    name: 'Avatar',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Styled div with background and initial',
    usedIn: ['OSLayout', 'SettingsPage'],
    description: 'Circular avatar with initial letter. Supports multiple sizes.',
    usageRule: 'Use for user profiles, team members, and contact avatars.',
    do: ['Use 2-3 initials max', 'Use accent color by default'],
    doNot: ['Do not use for non-person entities', 'Do not add borders'],
    tags: ['avatar', 'profile', 'user'],
  },
  {
    id: 'dropdown',
    name: 'Dropdown',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Custom CSS panel + shadow',
    usedIn: ['DesignSystemPage'],
    description: 'Floating dropdown menu with options list.',
    usageRule: 'Use for action menus and selection lists.',
    do: ['Show options on click', 'Close on outside click', 'Use box-shadow for elevation'],
    doNot: ['Do not use for navigation menus', 'Do not exceed 12 options without search'],
    tags: ['dropdown', 'menu', 'select'],
  },
  {
    id: 'modal',
    name: 'Modal',
    category: 'primitive',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'Custom CSS overlay + card',
    usedIn: ['DesignSystemPage'],
    description: 'Modal dialog overlay with title, body, and optional actions.',
    usageRule: 'Use for confirmations, forms, and detail views that require focus.',
    do: ['Show title and close button', 'Use max-width 480px for standard modals'],
    doNot: ['Do not stack modals', 'Do not use for navigation'],
    tags: ['modal', 'dialog', 'overlay'],
  },
]

