import type { ComponentMeta } from '../types'

export const workspaceComponents: ComponentMeta[] = [
  {
    id: 'command-center-page',
    name: 'CommandCenterPage',
    category: 'page',
    status: 'production',
    owner: 'command-center',
    version: '2.0.0',
    source: 'src/pages/os/CommandCenterPage.tsx',
    usedIn: ['/os/command-center route'],
    description: 'Main command center with system mood, division matrix, agent queue, and activity feed.',
    usageRule: 'Landing page after login. Read-only aggregation of all division models.',
    do: ['Show system mood derived from divisions', 'Surface top priorities and stale sources', 'Link to division detail pages'],
    doNot: ['Do not add write actions', 'Do not auto-refresh'],
    tags: ['page', 'command-center', 'dashboard'],
  },
  {
    id: 'investments-page',
    name: 'InvestmentsPage',
    category: 'page',
    status: 'production',
    owner: 'finance',
    version: '2.0.0',
    source: 'src/pages/os/InvestmentsPage.tsx',
    usedIn: ['/os/finance/investments route'],
    description: 'Investment overview with portfolio metrics, bucket view, dividend dashboard, DCA plans, and allocation.',
    usageRule: 'Main investment page. Tab-driven with 10 tabs.',
    do: ['Show portfolio summary first', 'Separate cash from securities', 'Use canonical dividend dataset'],
    doNot: ['Do not show write-back controls', 'Do not auto-refresh prices'],
    tags: ['page', 'finance', 'investments'],
  },
  {
    id: 'studio-workspace-page',
    name: 'StudioWorkspacePage',
    category: 'page',
    status: 'production',
    owner: 'studio',
    version: '2.0.0',
    source: 'src/pages/os/StudioWorkspacePage.tsx',
    usedIn: ['/os/studio/projects route'],
    description: 'Studio project list with project cards linking to detail pages.',
    usageRule: 'Project-first view. Redirects from /os/studio.',
    do: ['Show project cards with status and phase', 'Link to project detail with section navigation', 'Surface at-risk projects'],
    doNot: ['Do not show the old 8-tab dashboard by default'],
    tags: ['page', 'studio', 'projects'],
  },
  {
    id: 'studio-project-detail',
    name: 'StudioProjectDetailPage',
    category: 'page',
    status: 'production',
    owner: 'studio',
    version: '2.0.0',
    source: 'src/pages/os/StudioProjectDetailPage.tsx',
    usedIn: ['/os/studio/projects/:projectId route'],
    description: 'Project detail with sticky section navigation (Overview, Tasks, Timeline, Site, Documents, Reviews, AI).',
    usageRule: 'Navigated from project list or direct URL.',
    do: ['Sticky section nav for quick access', 'Overview shows Today/This Week summary', 'Site section includes Billing Gates placeholder'],
    doNot: ['Do not show empty sections as large panels', 'Do not remove the approval flow'],
    tags: ['page', 'studio', 'project-detail'],
  },
  {
    id: 'bridge-settings-page',
    name: 'BridgeSettingsPage',
    category: 'page',
    status: 'production',
    owner: 'ds-team',
    version: '1.0.0',
    source: 'src/pages/os/BridgeSettingsPage.tsx',
    usedIn: ['/os/bridge route'],
    description: 'Google Sheet bridge configuration, resource management, test connection, import/export, backups.',
    usageRule: 'Admin page. Not shown in user-facing navigation.',
    do: ['Show all sheet resources with column metadata', 'Include test connection button', 'Provide import preview before confirm'],
    doNot: ['Do not auto-sync', 'Do not show on production without authentication'],
    tags: ['page', 'admin', 'bridge'],
  },
]
